# nome da pipeline
name: Tests Cypress

# Quando a pipeline será executada
# Neste caso, toda vez que houver um pull request para a branch main
on:
  pull_request:
    branches: [main]

jobs:
  # Job: rodar os testes Cypress
  cypress-run:
    # Ambiente onde a pipeline vai rodar
    runs-on: windows-latest

    steps:
      # Clonar o projeto
      - name: Checkout do projeto
        uses: actions/checkout@v3

      # Executar Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
 